### ISSUE TITLE
Positioning on screen

### ISSUE THREAD

**Issue by vovkkk** [facelessuser/sublime-markdown-popups#13] opened 2016-08-07 09:08 UTC
I’m not sure if it is right repo to report, but ColorHelper places pop-up under dock
Windows 8.1 Enterprise 32bit
ST 3120
ColorHelper installed just several minute ago, so the latest version, as well as dependencies

Is it bug of ST?

![2016-08-07_15-41-13](https://cloud.githubusercontent.com/assets/1975298/17461490/228d2b96-5cb8-11e6-8686-49c1ba68aebf.png)

**Comment by facelessuser** [comment] 2016-08-07 15:05
Unfortunately, this is a Sublime thing.  Sublime allows me to specify a cursor position in a view to show the popup at, **but** it is supposed to then resize and reposition according to your window size, which it does do.  The problem is that Sublime doesn't check for any Windows UI controls, and that is why it appears under the start menu.  I can't recall if it si specific to Windows 10 only as all the Windows computers I interface with currently are Windows 10.  Regardless, there isn't much I can do about it.  You could file an issue with Sublime though.

**Comment by facelessuser** [comment] 2016-08-07 15:05
As this is not a valid mdpopup issue and actually lies within Sublime, I will close this.

**Closed by facelessuser** 2016-08-07 15:05 UTC
Labels: Invalid
